### ISSUE TITLE
[Crash] Server Freezes, eventually watchdog kills it.

### ISSUE THREAD

**Issue by WhitePhant0m** [SuperMartijn642/Entangled1.12#43]
**Version Info**
- Minecraft, 1.19.2
- Entangled, 1.3.11b-forge-mc1.19

**Steps to Reproduce**
Not sure.

**Crash report (~/logs/latest.log)**

https://paste.gg/p/anonymous/1f3eb14c821a47dd81b72dac8646411f

All I know about this is that the server freezes when I load the chunk(s) that contain the entangled blocks.

Not sure what is causing it, and not even sure if it is indeed being caused by Entangled, but it's the one popping up in the crash log.

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.3.12.

Thank you for reporting the issue!

**Comment by bigenergy** [comment]
> Fixed now in version 1.3.12.
> 
> Thank you for reporting the issue!

not fixed
https://gist.github.com/bigenergy/2820e8e5031d273d3e83108281d541f7

Entangled 1.3.12
mc 1.18.2
